### ISSUE TITLE
built in support for oxd 3.1.1

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cred-manager#1]
To simplify the process of sending users from Credential Manager to an OpenID Provider like the Gluu Server for login, we should write a plugin for the  [oxd service](https://gluu.org/docs/oxd). 

The oxd / federated login configuration interfaces in the Credential Manager application could resemble the oxd plugin interfaces we wrote for other web apps, like the screens shown below:

(show's use of oxd web):   
![image](https://user-images.githubusercontent.com/5271048/29836102-c6864520-8cb9-11e7-89c5-97a8aa5fd5f8.png)

![image](https://user-images.githubusercontent.com/5271048/29779067-0c9daf50-8bd7-11e7-9123-3cc882f73e18.png)

![image](https://user-images.githubusercontent.com/5271048/29779071-0f266ec4-8bd7-11e7-9d6b-c76d96521f00.png)

![image](https://user-images.githubusercontent.com/5271048/29779103-2b66b83c-8bd7-11e7-8303-826b1726f1e8.png)

**Comment by jgomer2001** [comment]
Most configs not needed actually.

But we need to support newer oxd 3.1.1, for instance the https extension
