### ISSUE TITLE
oxAuth | Give users the ability to pick which phone number to send the sms to

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/cred-manager#10]
If a user has chosen to receive an OTP via SMS as preferred method of authentication, and have added two or more phone numbers, when he tries to authenticate he should be able to choose which phone to send the sms to.

A list should be displayed showing only the last 4 digits for every phone giving him the possibility to choose from there.

**Comment by willow9886** [comment]
See below for how Duo handles this situation of allowing the user to specify their device:

![image](https://user-images.githubusercontent.com/5271048/32860111-3fe14f02-ca16-11e7-884a-0a20d5b7741b.png)

**Comment by jgomer2001** [comment]
Fixed with https://github.com/GluuFederation/cred-manager/blob/f37fb304f0eee955eee3997d653b11353cd9995c/assets/cred-manager-external_twilio_sms.py as part of new general cred-manager custom script (see #46)
