### ISSUE TITLE
Credential Manager Documentation

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cred-manager#2]
Things to cover:

- setup with config files, etc.
- use of oxd
- adding custom branding (replace logos, change content, etc.)
- deployment (I assume we will just bundle this in our Gluu Server ce packages?)
- anything else you can think of...

I will create a new repo for credential manager docs.

**Comment by jgomer2001** [comment]
Already have this: https://github.com/GluuFederation/cred-manager/blob/master/app/README.md which covers configuration, installation, and some troubleshooting

This one https://github.com/GluuFederation/cred-manager/blob/master/app/developer-notes.md is more developer-oriented

**Comment by yurem** [comment]
In configuration we can replace "u2f_relative_uri" with server name "issuer". And using this name cred_mgr can always get Fido U2F metadata using URL like this: https://ce-dev.gluu.org/.well-known/fido-u2f-configuration

**Comment by jgomer2001** [comment]
I see your point. If "u2f_settings" is not provided or is null, it actually defaults to issuer + the well-known . This is only aimed at being used at development or testing environments where Apache is not present and thus the  .well-known... URL does not exist.
Just need to fix a bit the documentation...

**Comment by willow9886** [comment]
created the cred manager docs repo: https://github.com/GluuFederation/docs-credmanager-prod

**Comment by jgomer2001** [comment]
Added missing instructions for custom branding: https://github.com/GluuFederation/cred-manager/commit/e8916b2758f07ebb9ae09e1227c7a16ce8e816f7

**Comment by jgomer2001** [comment]
Repo structured for mkdocs now: https://github.com/GluuFederation/docs-credmanager-prod/commit/7e630abde456ecf8dc39c1325512be096ca7bbdf

**Comment by jgomer2001** [comment]
From the admin side docs are currently detailed. Now the user-ended stuff needs attention

**Comment by jgomer2001** [comment]
Pending tests of installation process to update the installation docs accordingly
