### ISSUE TITLE
Social login plugin

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cred-manager#23]
In Gluu OpenLDAP, we store an attribute for users called `oxExternalUID` that correlates the user to existing identities in other IDPs. It's a multi-valued attribute that lists the external IDPs and the persons username. 

We should evaluate how we can use the Passport.js authentication middleware to give users the ability to add/delete their external identities (for example, their Facebook ID, their Google ID, their GitHub ID, etc.).

**Comment by jgomer2001** [comment]
Can anyone contribute with ideas on how to solve this issue?:

We have a java web app from which users should be able to "associate" their social accounts (in other words, the app has to simply add oxExternalUids)

The users are already existing (in gluu LDAP)

The idea is to leverage what gluu-passport already provides (all social strategies built-in) and not to reimplement the integration with social networks in Java again

The workflow should work like this:
1. A user already authenticated at cred-manager, clicks a button that reads "Add social network account"
1. A set of social sites is shown (those already supported by the current passport configured in the underlying gluu server installation)
1. The user chooses one site and is redirected there where their login credentials are requested
1. The user provides their credentials and is returned back to the application
1. The application adds a proper attribute oxExternalUid under the user's LDAP entry

**Comment by jgomer2001** [comment]
> We should evaluate how we can use the Passport.js authentication middleware

For this case the process of linking an account is not in the context of an authentication workflow (as you are already authenticated when you try to do the linking). 

A new endpoint was added in passport 3.1.4 to facilitate a simpler flow: 

application redirects browser to new endpoint -> passport takes you to social site for auth -> browser is taken to passport's redirect uri -> passport posts signed user's profile to an endpoint in application -> linking occurs if message posted is understandable

**Comment by jgomer2001** [comment]
New Issue at https://github.com/GluuFederation/casa-ee-plugins/issues/7
