### ISSUE TITLE
Quick design customization

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cred-manager#26]
It would be nice to give orgs the ability to quickly set a color scheme and upload a logo. The existing customization options are great, but it would be nice to be able to quickly brand this for your org without creating a whole html/css page design. 

We could give the following easy customization options:

Main banner color: `choose/specify hex value`
Button color: `choose/specify hex value`
Upload logo: `attach file`

**Comment by jgomer2001** [comment]
Also added secondary buttons' color, favicon uploader, and panel header color
