### ISSUE TITLE
Give admin/user control over when they are presented for strong auth

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cred-manager#30]
We should give admins and users some basic control over when 2FA is applied. This setting will be applied whenever an  application does not explicitly request a certain form of authentication via the `acr_value`. 

Basically this is an enhancement to the authentication script, and then giving admins and users some control via the interface. 

We could make the options check boxes and allow the admin or user to select the desired checkboxes. 

## 2FA Enforcement Policy (Admin)
- Enforce strong authentication for every login attempt. (if checked, would disable all other options)

- Prompt for 2FA when the IP address is unrecognized. 

- Prompt for 2FA when the device is unrecognized. 

- Allow the user to set their own strong authentication policy. (if checked, would disable all other options)

## 2FA Enforcement Policy (User)

If the admin chooses option 4 (allow users to self-set), then we should give the user the following options:

- Enforce strong authentication upon every login attempt. (if checked, would disable all other options)

- Prompt for 2FA when my IP address is unrecognized. 

- Prompt for 2FA when my device is unrecognized. 

_______________

**Comment by jgomer2001** [comment]
Part of release 3.1.3
