### ISSUE TITLE
Add auditing capabilities

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/cred-manager#31]
In the near feature, we should log login attempts. Of special attention those under the circumstances listed in #30:
*  When IP address unrecognized
* When the device is unrecognized

We may also add e-mail notifications to users when these "suspicious" logins occur

The admin needs to be able to use this information (searches, reports...)

**Comment by willow9886** [comment]
We should have a broader discussion about metrics, auditing, and reporting orgs might find useful.

**Comment by willow9886** [comment]
Moved this to [Casa](https://github.com/GluuFederation/casa/issues/11)
