### ISSUE TITLE
Modularize cust script used for authentication

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/cred-manager#46]
Targeting issue #34, we need to provide an easy way for customers to plug their authentication mechanisms

Current cust script is huge & monolithic so should be divided into modules to not overwhelm developers. This also reduces the chances of breaking the script functionality

**Comment by yurem** [comment]
We implemented simular approach in CAS2_DUO [script](https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/cas2_duo). It imports CAS2 and DUO scripts and works as proxy.
We can go further and refactor scripts which you are going to use to simplify integration.

**Comment by jgomer2001** [comment]
Newer strategy dynamically loads external scripts on demand, thus not requiring any sort of modification to main script. 
Users who want to plug a new auth method just will need to write a custom script for it (and the respective plugin for the app afterwards) just keeping a few simple constraints in mind. All of this will be described  in docs
