### ISSUE TITLE
Enroll failed with QR scanning in SuperGluu

### ISSUE THREAD

**Issue by NazarYavornytskyy** [GluuFederation/cred-manager#7]
So, I've just wanna add device, after scanning QR code I got next error:
09-21 18:08:27.041 14268-14268/gluu.org.super.gluu I/Ads: Starting ad request.
09-21 18:08:27.041 14268-14268/gluu.org.super.gluu I/Ads: Use AdRequest.Builder.addTestDevice("71CBE2337D1B1A8DCAE0940800E2E277") to get test ads on this device.
09-21 18:08:27.101 14268-14292/gluu.org.super.gluu D/FA: Logging event (FE): _aq, Bundle[{_o=am, _sc=GluuMainActivity, _si=1666706152553197177, _aeid=1666706152553197203}]
09-21 18:08:27.591 14268-14470/gluu.org.super.gluu V/communication-service: Response code is:200
09-21 18:08:27.591 14268-14470/gluu.org.super.gluu I/process-fragment: Loaded U2f metadata: org.gluu.super_gluu.model.U2fMetaData@25a21faf
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu I/process-fragment: Authentication method: enroll
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu D/communication-service: Attempting to execute get with parameters: {username=mike, session_state=89ef4dc6-a72a-499f-bcd8-8deb43f5bd79, application=https://cred-manager.gluu.org/cred-manager/}
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu D/communication-service: username = mike
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu D/communication-service: session_state = 89ef4dc6-a72a-499f-bcd8-8deb43f5bd79
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu D/communication-service: application = https://cred-manager.gluu.org/cred-manager/
09-21 18:08:27.601 14268-14470/gluu.org.super.gluu I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-21 18:08:27.762 14268-14470/gluu.org.super.gluu V/communication-service: Response code is:406
09-21 18:08:27.762 14268-14470/gluu.org.super.gluu E/process-fragment: https://cred-manager.gluu.org/oxauth/seam/resource/restv1/fido/u2f/registration?username=mike&session_state=89ef4dc6-a72a-499f-bcd8-8deb43f5bd79&application=https%3A%2F%2Fcred-manager.gluu.org%2Fcred-manager%2F
                                                                       java.io.FileNotFoundException: https://cred-manager.gluu.org/oxauth/seam/resource/restv1/fido/u2f/registration?username=mike&session_state=89ef4dc6-a72a-499f-bcd8-8deb43f5bd79&application=https%3A%2F%2Fcred-manager.gluu.org%2Fcred-manager%2F
                                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:210)
                                                                           at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                           at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                           at org.gluu.super_gluu.net.CommunicationService.get(CommunicationService.java:73)
                                                                           at org.gluu.super_gluu.app.ProcessManager$2.run(ProcessManager.java:251)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by jgomer2001** [comment]
U2F implementation does not let us add more than one supergluu device to the same user:

An excerpt of oxauth.log

```
 ERROR [qtp1279149968-12] [oxauth.ws.rs.fido.u2f.U2fRegistrationWS] (U2fRegistrationWS.java:130) - Exception happened
org.xdi.oxauth.model.fido.u2f.exception.RegistrationNotAllowed: It's not possible to start registration with user_name and session_state becuase user 'mike' has already enrolled device
```

When removing the currently enrolled device, and try adding a fresh one, it works.

**Comment by jgomer2001** [comment]
Relates to #11
